### ISSUE TITLE
[feat]: hiding specific code

### ISSUE THREAD

**Issue by RSS1102** [liting-yes/vite-plugin-vue-preview#104]
I have some code that I don't want users to make changes to.

Can it be prohibited from being modified or directly hidden?

**Comment by litingyes** [comment]
for example

**Comment by RSS1102** [comment]
I hope the`<template>`cannot be changed, only the`<script>` can be changed.
![image](https://github.com/liting-yes/vite-plugin-vue-preview/assets/81673017/c4893f03-575a-4ca8-a147-7f8fe9a34c67)

---
Or his entire page cannot be changed, but it can be displayed on the page (`<template>` and `<script>` ),The file he introduced can be changed on the code page. And it takes effect immediately.
![image](https://github.com/liting-yes/vite-plugin-vue-preview/assets/81673017/fe6638ff-788e-492b-a261-e56537f17418)

**Comment by litingyes** [comment]
Can add a feature that disable everything

**Comment by litingyes** [comment]
But if you just want to disable the editing of some code snippets, codemirror shouldn't be able to do it. I haven't heard of any code editor that can do it.

**Comment by RSS1102** [comment]
> But if you just want to disable the editing of some code snippets, codemirror shouldn't be able to do it. I haven't heard of any code editor that can do it.

Can the second method be implemented?

**Comment by litingyes** [comment]
> > But if you just want to disable the editing of some code snippets, codemirror shouldn't be able to do it. I haven't heard of any code editor that can do it.
> 
> Can the second method be implemented?

hide something ?

**Comment by RSS1102** [comment]
i want to have to file:
1. Load unchanged content, but do not display it in the code editor.
2. loading on code editor, user can change it.

**Comment by litingyes** [comment]
I haven't thought of a good way to implement the function you mentioned. PR is welcome.

**Comment by RSS1102** [comment]
> I haven't thought of a good way to implement the function you mentioned. PR is welcome.

ok, I am not sure if this can be achieved, but the requirements and ideas are as follows. I can try PR after learning.

**Comment by litingyes** [comment]
First understand this : https://github.com/vuejs/repl ， good luck to you

**Comment by RSS1102** [comment]
> First understand this : https://github.com/vuejs/repl ， good luck to you

Okay, thank you. I'm trying to understand.
